title: Van Nguyen # your name (or website title) here
logo: "/images/Van_portrait.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Postdoctoral Research Fellow in Software Systems and Cybersecurity at Monash University, Australia.
  <br><br>
  <a href="https://scholar.google.com/citations?user=kLtEOdwAAAAJ&hl=en">View My Google Scholar</a> 

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
